name: Create release

on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Get project version
        run: |
          PROJECT_VERSION=$(poetry version --short)
          echo "::set-output name=version::$PROJECT_VERSION"
        id: version
      - name: Check if tag version matches project version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          echo $TAG
          if [[ "$TAG" != "v${{ steps.version.outputs.version }}" ]]; then exit 1; fi
      - name: release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          generateReleaseNotes: true
          name: ${{ steps.version.outputs.version }}
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install the project dependencies
        run: poetry install --with dev --no-root
      - name: Build poetry project
        run: |
          poetry build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl